### ISSUE TITLE
content.js 是否与本扩展无关？

### ISSUE THREAD

**Issue by wuchangfeng** [xlzd/zhfishhook#1]
你好，刚开始学习扩展的开发。看到项目文件有 content.js 与这个项目是否没有关系？

**Comment by xlzd** [comment]
确实是无关的，代码模板是从 zhjail（<a href="https://zhuanlan.zhihu.com/p/22107246">https://zhuanlan.zhihu.com/p/22107246</a>） 上复制的，我对浏览器插件也是照猫画虎，多谢提醒~~~

**Comment by wuchangfeng** [comment]
嘿嘿，great job.
